# Generated by Django 6.0.3 on 2026-04-01 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_itmaintenancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('forwarded', 'Forwarded'), ('returned', 'Returned'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('meeting', 'Meeting'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('teams_join_url', models.URLField(max_length=1000)),
                ('teams_meeting_id', models.CharField(blank=True, max_length=255)),
                ('teams_external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to='coreapp.staff')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to='coreapp.staff')),
            ],
            options={
                'ordering': ['start_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='coreapp.meeting'),
        ),
    ]
