# Generated by Django 6.0.3 on 2026-04-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_alter_notification_notification_type_meeting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='meeting',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('forwarded', 'Forwarded'), ('returned', 'Returned'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('message', 'Message'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='coreapp.staff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='staff_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='coreapp.staffmessage'),
        ),
        migrations.CreateModel(
            name='StaffMessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='coreapp.staff')),
                ('staff_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='coreapp.staffmessage')),
            ],
            options={
                'ordering': ['-staff_message__created_at'],
                'unique_together': {('staff_message', 'recipient')},
            },
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
