# Generated by Django 6.0.3 on 2026-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_remove_notification_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AlterField(
            model_name='staffmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
